import {
  Code,
  Palette,
  TrendingUp,
  Users,
  Megaphone,
  HeartPulse,
  GraduationCap,
  Building2,
  Truck,
  Briefcase,
  Wallet,
  Wrench,
  ShieldCheck,
  Leaf,
  Film,
  Scale,
  Cpu,
  Database,
  TestTube,
  Layers,
  Headphones,
  Settings,
  FileSearch,
  UserCog,
  LineChart,
} from "lucide-react";

export const DOMAIN_ICON_MAP: Record<string, React.ComponentType<any>> = {
  "Software Engineering": Code,
  Backend: Database,
  Frontend: Layers,
  "Full-stack": Layers,
  Android: Cpu,
  DevOps: Settings,
  "AI / Data Science": LineChart,
  "Design / Creative": Palette,
  "Product / Project": Briefcase,
  "Customer Acquisition": Megaphone,
  "Support / Customer Success": Headphones,
  "Talent / HR": Users,
  "Accounts / Finance": Wallet,
  Operations: Wrench,
  Legal: Scale,
  "QA / Testing": TestTube,
  Admin: UserCog,
  "Admin / Office": UserCog,
  Research: FileSearch,
  Analyst: LineChart,
  Other: Briefcase,
};

export function getDomainIcon(domainName: string) {
  return DOMAIN_ICON_MAP[domainName] || Briefcase;
}
