// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/*";
  };
  "routes/layout.tsx": {
    id: "routes/layout";
    page: "/" | "/about" | "/*";
  };
  "routes/LandingPage.tsx": {
    id: "routes/LandingPage";
    page: "/";
  };
  "routes/About.tsx": {
    id: "routes/About";
    page: "/about";
  };
  "routes/NotFound.tsx": {
    id: "routes/NotFound";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/layout": typeof import("./app/routes/layout.tsx");
  "routes/LandingPage": typeof import("./app/routes/LandingPage.tsx");
  "routes/About": typeof import("./app/routes/About.tsx");
  "routes/NotFound": typeof import("./app/routes/NotFound.tsx");
};